<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jitdataset" nsURI="http://www.neoflex.ru/meta/jitdataset" nsPrefix="jitdataset">
  <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScalarType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
        eType="ecore:EEnum http://www.neoflex.ru/meta/dataset#//DataTypeDomain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LookupType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lookupField" eType="#//DsField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DsField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
        eType="#//DataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataset" eType="#//AbstractDataset"
        eOpposite="#//AbstractDataset/dataFields"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isVisible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterField" eSuperTypes="#//DsField"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifiedField" eSuperTypes="#//DsField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruleOption" eType="#//RuleExecutionOption"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dataset" eSuperTypes="#//AbstractDataset">
    <eOperations name="validate">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="РџСЂРѕРІРµСЂРёС‚СЊ"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="activate">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="РђРєС‚РёРІРёСЂРѕРІР°С‚СЊ"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="activateClassification">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="РђРєС‚РёРІРёСЂРѕРІР°С‚СЊ РєР»Р°СЃСЃРёС„РёРєР°С†РёСЋ"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="loadFromFile">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="Р—Р°РіСЂСѓР·РёС‚СЊ РёР· С„Р°Р№Р»Р°"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="build">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="РЎРѕР±СЂР°С‚СЊ"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="classify">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="РџСЂРѕРєР»Р°СЃСЃРёС„РёС†РёСЂРѕРІР°С‚СЊ"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="repairTables">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="Р’РѕСЃСЃС‚Р°РЅРѕРІРёС‚СЊ С‚Р°Р±Р»РёС†С‹"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="export">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="Р­РєСЃРїРѕСЂС‚РёСЂРѕРІР°С‚СЊ"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buildSpec" eType="#//DsBuildSpec"
        containment="true" eOpposite="#//DsBuildSpec/dataset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classificationFieldSpecs"
        upperBound="-1" eType="#//ClassificationFieldSpec" containment="true" eOpposite="#//ClassificationFieldSpec/dataset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeploymentDescriptor">
    <eOperations name="activate">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="РђРєС‚РёРІРёСЂРѕРІР°С‚СЊ"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasets" upperBound="-1"
        eType="#//AbstractDataset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hiveConnection" eType="ecore:EClass http://www.neoflex.ru/meta/rt#//JdbcConnection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hiveDatabaseName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hdfsNameNode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hdfsBaseDirectory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hdfsIncomeFilesDirectory"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hdfsUser" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webHdfsUtl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sparkJobServer" eType="ecore:EClass http://www.neoflex.ru/meta/rt#//JobServer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biServerUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="ecore:EClass http://www.neoflex.ru/meta/etl#//Project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployments" upperBound="-1"
        eType="ecore:EClass http://www.neoflex.ru/meta/rt#//Deployment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="zeppelinConnection" eType="#//ZeppelinConnection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DsBuildSpec" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataset" eType="#//Dataset"
        eOpposite="#//Dataset/buildSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTBuildSpec" eSuperTypes="#//DsBuildSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subquery" eType="#//Subquery"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SQLBuildSpec" eSuperTypes="#//DsBuildSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sql" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@Column(length=10485760)"/>
      </eAnnotations>
      <eAnnotations source="mspace.ui">
        <details key="multiline" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedDatasets" upperBound="-1"
        eType="#//DatasetReference" containment="true" eOpposite="#//DatasetReference/buildSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassificationFieldSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataset" eType="#//Dataset"
        eOpposite="#//Dataset/classificationFieldSpecs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsField" eType="#//ClassifiedField">
      <eAnnotations source="mspace.ui">
        <details key="filter" value="auto"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//ClassificationRule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultExpr" eType="#//ConstantExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subquery" eType="#//Subquery"
        eOpposite="#//Subquery/joinClause"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableReference" lowerBound="1"
        eType="#//TableReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinedReference" upperBound="-1"
        eType="#//JoinedReference" containment="true" eOpposite="#//JoinedReference/joinClause"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinedReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinClause" eType="#//JoinClause"
        eOpposite="#//JoinClause/joinedReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="joinType" lowerBound="1"
        eType="#//JoinType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinExpr" upperBound="-1"
        eType="#//JoinedFields" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinedReference" lowerBound="1"
        eType="#//TableReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableReference" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldSpecs" upperBound="-1"
        eType="#//DsFieldSpec" containment="true" eOpposite="#//DsFieldSpec/tableReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subquery" eSuperTypes="#//TableReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinClause" lowerBound="1"
        eType="#//JoinClause" containment="true" eOpposite="#//JoinClause/subquery"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whereClause" eType="#//BinaryExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unionSubquery" eType="#//UnionSubquery"
        containment="true" eOpposite="#//UnionSubquery/subquery"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatasetReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buildSpec" eType="#//SQLBuildSpec"
        eOpposite="#//SQLBuildSpec/usedDatasets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataset" lowerBound="1"
        eType="#//AbstractDataset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterConstraints" upperBound="-1"
        eType="#//ParameterConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DsFieldSpec" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" eType="#//DataType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableReference" eType="#//TableReference"
        eOpposite="#//TableReference/fieldSpecs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DsReferenceFieldSpec" eSuperTypes="#//DsFieldSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedField" eType="#//DsField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubqueryFieldSpec" abstract="true" eSuperTypes="#//DsFieldSpec"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubqueryReferenceFieldSpec" eSuperTypes="#//DsFieldSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedFieldSpec" eType="#//DsFieldSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionRuleSpec" eSuperTypes="#//SubqueryFieldSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinedFields">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootSide" eType="#//DsFieldSpec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinedSide" eType="#//DsFieldSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JoinType">
    <eLiterals name="INNER"/>
    <eLiterals name="LEFT_OUTER" value="1"/>
    <eLiterals name="RIGHT_OUTER" value="2"/>
    <eLiterals name="FULL_OUTER" value="3"/>
    <eLiterals name="CROSS_JOIN" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnionSubquery">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subquery" eType="#//Subquery"
        eOpposite="#//Subquery/unionSubquery"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//ParameterField"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="#//Op"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sqlExpr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Op">
    <eLiterals name="AND"/>
    <eLiterals name="OR" value="1"/>
    <eLiterals name="NOT" value="2"/>
    <eLiterals name="EQUAL" value="3"/>
    <eLiterals name="NOT_EQUAL" value="4"/>
    <eLiterals name="LESSER" value="5"/>
    <eLiterals name="GREATER" value="6"/>
    <eLiterals name="LESSER_OR_EQUAL" value="7"/>
    <eLiterals name="GRATER_OR_EQUAL" value="8"/>
    <eLiterals name="LIKE" value="9"/>
    <eLiterals name="IN" value="10"/>
    <eLiterals name="PLUS" value="11"/>
    <eLiterals name="MINUS" value="12"/>
    <eLiterals name="MUL" value="13"/>
    <eLiterals name="DIV" value="14"/>
    <eLiterals name="IS_NULL" value="15"/>
    <eLiterals name="IS_NOT_NULL" value="16"/>
    <eLiterals name="IS_EMPTY" value="17"/>
    <eLiterals name="IS_NOT_EMPTY" value="18"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeOps">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
        eType="ecore:EEnum http://www.neoflex.ru/meta/dataset#//DataTypeDomain"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availableOps" upperBound="-1"
        eType="#//Op"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParamEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//ParameterField"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expr" abstract="true">
    <eOperations name="eval" eType="#//ScalarType">
      <eParameters name="parameters" upperBound="-1" eType="#//ParamEntry"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpr" eSuperTypes="#//NonTerminalExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//Op"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpr" eSuperTypes="#//NonTerminalExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//Op"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TerminalExpr" abstract="true" eSuperTypes="#//Expr"/>
  <eClassifiers xsi:type="ecore:EClass" name="FieldRefExpr" eSuperTypes="#//TerminalExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldRef" eType="#//DsField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterExpr" eSuperTypes="#//TerminalExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//ParameterField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantExpr" eSuperTypes="#//TerminalExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requireTypeCast" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassificationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classificationExpressions"
        upperBound="-1" eType="#//ClassificationExpression" containment="true" eOpposite="#//ClassificationExpression/rule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassificationExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//ClassificationRule"
        eOpposite="#//ClassificationRule/classificationExpressions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
        eType="#//NonTerminalExpr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportDataset" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reportForm" eType="#//ReportForm"
        eOpposite="#//ReportForm/datasets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataset" eType="#//AbstractDataset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterConstraints" upperBound="-1"
        eType="#//ParameterConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sortByFields" upperBound="-1"
        eType="#//FieldSort" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KlikoExportDataset" eSuperTypes="#//ExportedDataset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="klikoField" eType="#//DsField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DetalizationDataset" eSuperTypes="#//ReportDataset"/>
  <eClassifiers xsi:type="ecore:EClass" name="SummaryDataset" eSuperTypes="#//ReportDataset"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReportParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterType" eType="ecore:EEnum http://www.neoflex.ru/meta/dataset#//DataTypeDomain"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lookupField" eType="#//DsField"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reportForm" eType="#//ReportForm"
        eOpposite="#//ReportForm/parameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportParameterValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//ReportParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ConstantExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportForm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasets" upperBound="-1"
        eType="#//ReportDataset" containment="true" eOpposite="#//ReportDataset/reportForm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ReportParameter" containment="true" eOpposite="#//ReportParameter/reportForm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="ecore:EClass http://www.neoflex.ru/meta/etl#//Project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auditInfo" eType="ecore:EClass http://www.neoflex.ru/meta/auth#//AuditInfo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Status">
    <eLiterals name="NOT_STARTED"/>
    <eLiterals name="WORK_IN_PROGRESS" value="1"/>
    <eLiterals name="FINISHED" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AppUser" eSuperTypes="http://www.neoflex.ru/meta/auth#//UserInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Report">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deadlineDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signingDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//Status"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibleUser" eType="#//AppUser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reportForm" eType="#//ReportForm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterValues" upperBound="-1"
        eType="#//ReportParameterValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auditInfo" eType="ecore:EClass http://www.neoflex.ru/meta/auth#//AuditInfo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LookupDataset" eSuperTypes="#//Dataset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lookupField" eType="#//DsField"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayField" eType="#//DsField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExportedDataset" eSuperTypes="#//ReportDataset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldsToExport" upperBound="-1"
        eType="#//DsField"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exportFormat" eType="#//ExportFormat"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CsvExportedDataset" eSuperTypes="#//ExportedDataset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldDelimiter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="|"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeHeaders" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuncallExpr" eSuperTypes="#//TerminalExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fun" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SortDirection">
    <eLiterals name="ASC"/>
    <eLiterals name="DESC" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldSort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//DsField"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sortDirection" eType="#//SortDirection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDataset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="businessName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datasetDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataFields" upperBound="-1"
        eType="#//DsField" containment="true" eOpposite="#//DsField/dataset"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataAnalysisLink" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publications" upperBound="-1"
        eType="#//DatasetPublication" containment="true" eOpposite="#//DatasetPublication/dataset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="ecore:EClass http://www.neoflex.ru/meta/etl#//Project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auditInfo" eType="ecore:EClass http://www.neoflex.ru/meta/auth#//AuditInfo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalDataset" eSuperTypes="#//AbstractDataset">
    <eOperations name="refreshScheme">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="РћР±РЅРѕРІРёС‚СЊ СЃС…РµРјСѓ"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sqlExpr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@Column(length=10485760)"/>
      </eAnnotations>
      <eAnnotations source="mspace.ui">
        <details key="multiline" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="ecore:EClass http://www.neoflex.ru/meta/etl#//Context"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExportFormat" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CsvFormat" eSuperTypes="#//ExportFormat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldDelimiter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="|"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quoteField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeHeaders" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExcelFormat" eSuperTypes="#//ExportFormat"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationLogEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="finishTs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datasetName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@Column(length=10485760)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opStatus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@Column(length=10485760)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZeppelinConnection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="ecore:EClass http://www.neoflex.ru/meta/etl#//Project"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatasetPublication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataset" eType="#//AbstractDataset"
        eOpposite="#//AbstractDataset/publications"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KlikoFormat" eSuperTypes="#//ExportFormat"/>
  <eClassifiers xsi:type="ecore:EClass" name="DatasetNavigation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="ecore:EClass http://www.neoflex.ru/meta/etl#//Project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataset" eType="#//AbstractDataset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigationItems" upperBound="-1"
        eType="#//DatasetNavigationItem" containment="true" eOpposite="#//DatasetNavigationItem/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatasetNavigationItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//DatasetNavigation"
        eOpposite="#//DatasetNavigation/navigationItems"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toDataset" eType="#//AbstractDataset"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RuleExecutionOption">
    <eLiterals name="OVERWRITE"/>
    <eLiterals name="CONCATENATE" value="1"/>
    <eLiterals name="INSERT_NEW" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonTerminalExpr" abstract="true" eSuperTypes="#//Expr"/>
</ecore:EPackage>
