version: "3.7"
services:
  hivemetastore:
    image: postgres:11.5
    restart: always
    hostname: hivemetastore
    environment:
      POSTGRES_PASSWORD: new_password
    ports:
      - 5532:5432
    expose:
      - 5432
    volumes:
      - ./pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      bd_net:
        ipv4_address: 172.20.1.4

  master:
    image: neoflexdatagram/bd-base
    build: ./bd-base
    hostname: master
    depends_on:
      - hivemetastore
    environment:
      HADOOP_NODE: namenode
      HIVE_CONFIGURE: yes, please
      SPARK_PUBLIC_DNS: localhost
      SPARK_LOCAL_IP: 172.20.1.1
      SPARK_MASTER_HOST: 172.20.1.1
      SPARK_LOCAL_HOSTNAME: master
    expose:
      - 1-65535
    ports:
      # Spark Master Web UI
      - 8080:8080
      # Spark job Web UI: increments for each successive job
      - 4040:4040
      - 4041:4041
      - 4042:4042
      - 4043:4043
      # Spark History server
      - 18080:18080
      # YARN UI
      - 8088:8088
      # Hadoop namenode UI
      - 9870:9870
      # Hadoop secondary namenode UI
      - 9868:9868
      # Hive JDBC
      - 10000:10000
      # webhdfs
      - 51070:50070
    volumes:
      - dfs_name:/dfs/name
      - ./bd-base/data:/data
      - ./bd-base/extralib:/extralib
      - ../spark2lib/target/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0.0-SNAPSHOT.jar:/extralib/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0.0-SNAPSHOT.jar
      - ../runtime/target/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0.0-SNAPSHOT.jar:/extralib/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0.0-SNAPSHOT.jar
    networks:
      bd_net:
        ipv4_address: 172.20.1.1
    extra_hosts:
      - "master:172.20.1.1"
      - "worker1:172.20.1.2"
      - "worker2:172.20.1.3"
      - "hivemetastore:172.20.1.4"
      - "livy:172.20.1.6"

  worker1:
    image: neoflexdatagram/bd-base
    build: ./bd-base
    hostname: worker1
    depends_on:
      - hivemetastore
    environment:
      SPARK_MASTER_ADDRESS: spark://master:7077
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
      SPARK_LOCAL_HOSTNAME: worker1
      SPARK_LOCAL_IP: 172.20.1.2
      SPARK_MASTER_HOST: 172.20.1.1
      HADOOP_NODE: datanode
    expose:
      - 1-65535
    ports:
      # Hadoop datanode UI
      - 9864:9864
      #Spark worker UI
      - 8081:8081
      - 8042:8042
    volumes:
      - dfs_data_1:/dfs/data
      - ./bd-base/data:/data
      - ./bd-base/extralib:/extralib
      - ../spark2lib/target/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0.0-SNAPSHOT.jar:/extralib/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0.0-SNAPSHOT.jar
      - ../runtime/target/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0.0-SNAPSHOT.jar:/extralib/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0.0-SNAPSHOT.jar
    networks:
      bd_net:
        ipv4_address: 172.20.1.2
    extra_hosts:
      - "master:172.20.1.1"
      - "worker1:172.20.1.2"
      - "worker2:172.20.1.3"
      - "hivemetastore:172.20.1.4"
      - "livy:172.20.1.6"

  worker2:
    image: neoflexdatagram/bd-base
    build: ./bd-base
    hostname: worker2
    depends_on:
      - hivemetastore
    environment:
      SPARK_MASTER_ADDRESS: spark://master:7077
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_PUBLIC_DNS: localhost
      SPARK_LOCAL_HOSTNAME: worker2
      SPARK_LOCAL_IP: 172.20.1.3
      SPARK_MASTER_HOST: 172.20.1.1
      HADOOP_NODE: datanode
      HADOOP_DATANODE_UI_PORT: 9865
    expose:
      - 1-65535
    ports:
      # Hadoop datanode UI
      - 9865:9865
      # Spark worker UI
      - 8082:8082
      - 8043:8042
    volumes:
      - dfs_data_2:/dfs/data
      - ./bd-base/data:/data
      - ./bd-base/extralib:/extralib
      - ../spark2lib/target/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0.0-SNAPSHOT.jar:/extralib/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0.0-SNAPSHOT.jar
      - ../runtime/target/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0.0-SNAPSHOT.jar:/extralib/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0.0-SNAPSHOT.jar
    networks:
      bd_net:
        ipv4_address: 172.20.1.3
    extra_hosts:
      - "master:172.20.1.1"
      - "worker1:172.20.1.2"
      - "worker2:172.20.1.3"
      - "hivemetastore:172.20.1.4"
      - "livy:172.20.1.6"

  livy:
    image: neoflexdatagram/bd-livy
    build: ./bd-livy
    hostname: livy
    depends_on:
      - master
      - worker1
      - worker2
    volumes:
      - ./livy_batches:/livy_batches
      - ./bd-base/data:/data
      - ./bd-base/extralib:/extralib
      - ../spark2lib/target/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0.0-SNAPSHOT.jar:/extralib/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0.0-SNAPSHOT.jar
      - ../runtime/target/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0.0-SNAPSHOT.jar:/extralib/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0.0-SNAPSHOT.jar
      - ../spark2lib/target/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0.0-SNAPSHOT.jar:/usr/livy/repl_2.12-jars/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0.0-SNAPSHOT.jar
      - ../runtime/target/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0.0-SNAPSHOT.jar:/usr/livy/repl_2.12-jars/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0.0-SNAPSHOT.jar
    #      - ./bd-base/extralib/postgresql-42.2.12.jre6.jar:/usr/livy/repl_2.12-jars/postgresql-42.2.12.jre6.jar
    #      - ./bd-base/extralib/ojdbc8.jar:/usr/livy/repl_2.12-jars/ojdbc8.jar
    #      - ./bd-base/extralib/HiveJDBC4.jar:/usr/livy/repl_2.12-jars/HiveJDBC4.jar
    environment:
      - SPARK_MASTER=yarn
      # Intentionally not specified - if it's set here, then we can't override it
      # via REST API ("conf"={} map)
      # Can be client or cluster
      #      - SPARK_DEPLOY_MODE=client

      - LOCAL_DIR_WHITELIST=/data/batches/
      - ENABLE_HIVE_CONTEXT=true
      # Defaults are fine for variables below. Uncomment to change them.
    #      - LIVY_HOST=0.0.0.0
    #      - LIVY_PORT=8998
    expose:
      - 1-65535
    ports:
      - 8998:8998
    networks:
      bd_net:
        ipv4_address: 172.20.1.6
    extra_hosts:
      - "master:172.20.1.1"
      - "worker1:172.20.1.2"
      - "worker2:172.20.1.3"
      - "hivemetastore:172.20.1.4"
      - "livy:172.20.1.6"

  samples:
    image: neoflexdatagram/bd-samples
    build: ./bd-samples
    depends_on:
      - datagram
    networks:
      bd_net:
        ipv4_address: 172.20.1.9
    extra_hosts:
      - "master:172.20.1.1"
      - "worker1:172.20.1.2"
      - "worker2:172.20.1.3"
      - "hivemetastore:172.20.1.4"
      - "livy:172.20.1.6"

  oozie:
    image: neoflexdatagram/bd-oozie
    build: ./bd-oozie
    hostname: oozie
    depends_on:
      - master
      - worker1
      - worker2
    volumes:
      - ../spark2lib/target/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0.0-SNAPSHOT.jar:/usr/oozie/sharelib/lib/spark2/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0.0-SNAPSHOT.jar
      - ../runtime/target/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0.0-SNAPSHOT.jar:/usr/oozie/sharelib/lib/spark2/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0.0-SNAPSHOT.jar
      - ../spark2lib/target/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0.0-SNAPSHOT.jar:/usr/oozie/sharelib/lib/spark2/livy/repl_2.12-jars/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0.0-SNAPSHOT.jar
    expose:
      - 1-65535
    ports:
      - 11000:11000
    networks:
      bd_net:
        ipv4_address: 172.20.1.8
    extra_hosts:
      - "master:172.20.1.1"
      - "worker1:172.20.1.2"
      - "worker2:172.20.1.3"
      - "hivemetastore:172.20.1.4"
      - "livy:172.20.1.6"
      - "oozie:172.20.1.8"

  datagram:
    image: neoflexdatagram/datagram
    build: ./datagram
    hostname: datagram
    depends_on:
      - livy
    volumes:
      - ./datagram/gitflow:/opt/datagram/gitflow
      - ./datagram/logs:/opt/datagram/logs
      - ./datagram/mspace:/opt/datagram/mspace
      - ../mserver/target/mserver-spark3-2.0.0-SNAPSHOT.jar:/opt/datagram/mserver-spark3-2.0.0-SNAPSHOT.jar
      - ../spark2lib/target/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0-SNAPSHOT.jar:/root/.m2/repository/ru/neoflex/meta/etl2/ru.neoflex.meta.etl2.spark.spark2lib/spark3-2.0.0-SNAPSHOT/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0-SNAPSHOT.jar
      - ../spark2lib/.flattened-pom.xml:/root/.m2/repository/ru/neoflex/meta/etl2/ru.neoflex.meta.etl2.spark.spark2lib/spark3-2.0.0-SNAPSHOT/ru.neoflex.meta.etl2.spark.spark2lib-spark3-2.0.0-SNAPSHOT.pom
      - ../runtime/target/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0-SNAPSHOT.jar:/root/.m2/repository/ru/neoflex/meta/etl/ru.neoflex.meta.etl.spark.runtime/spark3-2.0.0-SNAPSHOT/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0-SNAPSHOT.jar
      - ../runtime/.flattened-pom.xml:/root/.m2/repository/ru/neoflex/meta/etl/ru.neoflex.meta.etl.spark.runtime/spark3-2.0.0-SNAPSHOT/ru.neoflex.meta.etl.spark.runtime-spark3-2.0.0-SNAPSHOT.pom
      - ../.flattened-pom.xml:/root/.m2/repository/ru/neoflex/parent/spark3-2.0.0-SNAPSHOT/parent-spark3-2.0.0-SNAPSHOT.pom
    expose:
      - 1-65535
    ports:
      - 8089:8089
    networks:
      bd_net:
        ipv4_address: 172.20.1.7
    extra_hosts:
      - "master:172.20.1.1"
      - "worker1:172.20.1.2"
      - "worker2:172.20.1.3"
      - "hivemetastore:172.20.1.4"
      - "livy:172.20.1.6"
      - "oozie:172.20.1.8"

###
networks:
  bd_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  dfs_name:
  dfs_data_1:
  dfs_data_2: