<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ui2" nsURI="http://www.neoflex.ru/meta/ui2" nsPrefix="ui2">
  <eClassifiers xsi:type="ecore:EClass" name="UIPackage">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x45f;&#x420;&#xb0;&#x420;&#x454;&#x420;&#xb5;&#x421;&#x201a; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x406;"/>
      <details key="caption.plural" value="&#x420;&#x45f;&#x420;&#xb0;&#x420;&#x454;&#x420;&#xb5;&#x421;&#x201a;&#x421;&#x2039; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x406;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45c;&#x420;&#xb0;&#x420;&#x451;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
        <details key="display" value="true"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiClasses" upperBound="-1" eType="//UIClass" containment="true" eOpposite="//UIClass/uiPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIClass">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x45b;&#x421;&#x201a;&#x420;&#x455;&#x420;&#xb1;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb0;&#x420;&#xb5;&#x420;&#x458;&#x421;&#x2039;&#x420;&#x2116; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;"/>
      <details key="caption.plural" value="&#x420;&#x45b;&#x421;&#x201a;&#x420;&#x455;&#x420;&#xb1;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb0;&#x420;&#xb5;&#x420;&#x458;&#x421;&#x2039;&#x420;&#xb5; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x421;&#x2039;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45c;&#x420;&#xb0;&#x420;&#x451;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseName" lowerBound="1">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x2018;&#x420;&#xb0;&#x420;&#xb7;&#x420;&#x455;&#x420;&#x406;&#x420;&#x455;&#x420;&#xb5; &#x420;&#x405;&#x420;&#xb0;&#x420;&#x451;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption" lowerBound="1">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x2014;&#x420;&#xb0;&#x420;&#x456;&#x420;&#x455;&#x420;&#xbb;&#x420;&#x455;&#x420;&#x406;&#x420;&#x455;&#x420;&#x454;"/>
        <details key="display" value="true"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qName" lowerBound="1">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x459;&#x420;&#x406;&#x420;&#xb0;&#x420;&#xbb;&#x420;&#x451;&#x421;&#x201e;&#x420;&#x451;&#x421;&#x2020;&#x420;&#x451;&#x421;&#x402;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x420;&#x455;&#x420;&#xb5; &#x420;&#x405;&#x420;&#xb0;&#x420;&#x451;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiPackage" lowerBound="1" eType="//UIPackage" eOpposite="//UIPackage/uiClasses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiForms" upperBound="-1" eType="//UIForm" containment="true" eOpposite="//UIForm/uiClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editForm" eType="//EditForm">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x401;&#x420;&#xb0;&#x420;&#xb1;&#x420;&#xbb;&#x420;&#x455;&#x420;&#x405; &#x421;&#x201e;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x421;&#x2039; &#x421;&#x402;&#x420;&#xb5;&#x420;&#x491;&#x420;&#xb0;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x451;&#x421;&#x402;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainListForm" eType="//MainListForm">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#xa4;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x420;&#xb0; &#x421;&#x403;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x454;&#x420;&#xb0;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainEditForm" eType="//MainEditForm">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#xa4;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x420;&#xb0; &#x421;&#x402;&#x420;&#xb5;&#x420;&#x491;&#x420;&#xb0;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x451;&#x421;&#x402;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hiers" upperBound="-1" eType="//UIClass">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45c;&#x420;&#xb0;&#x421;&#x403;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x491;&#x420;&#x405;&#x420;&#x451;&#x420;&#x454;&#x420;&#x451;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiOperations" upperBound="-1" eType="//UIOperation" containment="true" eOpposite="//UIOperation/uiClass">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45b;&#x420;&#x457;&#x420;&#xb5;&#x421;&#x402;&#x420;&#xb0;&#x421;&#x2020;&#x420;&#x451;&#x420;&#x451;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiSuperTypes" upperBound="-1" eType="//UIClass">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#xa0;&#x420;&#x455;&#x420;&#x491;&#x420;&#x451;&#x421;&#x201a;&#x420;&#xb5;&#x420;&#xbb;&#x420;&#x451;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="designerLink">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x201d;&#x420;&#x451;&#x420;&#xb7;&#x420;&#xb0;&#x420;&#x2116;&#x420;&#x405;&#x420;&#xb5;&#x421;&#x402;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiClass" lowerBound="1" eType="//UIClass" eOpposite="//UIClass/uiOperations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45c;&#x420;&#xb0;&#x420;&#x451;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeQName" lowerBound="1">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x459;&#x420;&#x406;&#x420;&#xb0;&#x420;&#xbb;&#x420;&#x451;&#x421;&#x201e;&#x420;&#x451;&#x421;&#x2020;&#x420;&#x451;&#x421;&#x402;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x420;&#x455;&#x420;&#xb5; &#x420;&#x451;&#x420;&#x458;&#x421;&#x40f; &#x421;&#x201a;&#x420;&#x451;&#x420;&#x457;&#x420;&#xb0;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption" lowerBound="1">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x2014;&#x420;&#xb0;&#x420;&#x456;&#x420;&#x455;&#x420;&#xbb;&#x420;&#x455;&#x420;&#x406;&#x420;&#x455;&#x420;&#x454;"/>
        <details key="display" value="true"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIForm" abstract="true" eSuperTypes="//Layout">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#xa4;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#xa4;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x421;&#x2039;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiClass" lowerBound="1" eType="//UIClass" eOpposite="//UIClass/uiForms"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="embeddedForms" upperBound="-1" eType="//UIForm">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x2019;&#x420;&#xbb;&#x420;&#x455;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x420;&#xb5; &#x421;&#x201e;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x421;&#x2039;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSources" upperBound="-1" eType="//DataSource" containment="true" eOpposite="//DataSource/form">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#xfffd;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x421;&#x2021;&#x420;&#x405;&#x420;&#x451;&#x420;&#x454;&#x420;&#x451; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditForm" eSuperTypes="//UIForm">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#xa4;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x420;&#xb0; &#x421;&#x402;&#x420;&#xb5;&#x420;&#x491;&#x420;&#xb0;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x451;&#x421;&#x402;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
      <details key="caption.plural" value="&#x420;&#xa4;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x421;&#x2039; &#x421;&#x402;&#x420;&#xb5;&#x420;&#x491;&#x420;&#xb0;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x451;&#x421;&#x402;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectItem" eType="//DataSource">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#xfffd;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x421;&#x2021;&#x420;&#x405;&#x420;&#x451;&#x420;&#x454; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#xb0;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainListForm" eSuperTypes="//UIForm">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x201c;&#x420;&#xbb;&#x420;&#xb0;&#x420;&#x406;&#x420;&#x405;&#x420;&#xb0;&#x421;&#x40f; &#x421;&#x201e;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x420;&#xb0; &#x421;&#x403;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x454;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#x201c;&#x420;&#xbb;&#x420;&#xb0;&#x420;&#x406;&#x420;&#x405;&#x421;&#x2039;&#x420;&#xb5; &#x421;&#x201e;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x421;&#x2039; &#x421;&#x403;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x454;&#x420;&#x455;&#x420;&#x406;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectList" lowerBound="1" eType="//ObjectList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entryPoint">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainEditForm" eSuperTypes="//EditForm">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x201c;&#x420;&#xbb;&#x420;&#xb0;&#x420;&#x406;&#x420;&#x405;&#x420;&#xb0;&#x421;&#x40f; &#x421;&#x201e;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x420;&#xb0; &#x421;&#x402;&#x420;&#xb5;&#x420;&#x491;&#x420;&#xb0;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x451;&#x421;&#x402;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
      <details key="caption.plural" value="&#x420;&#x201c;&#x420;&#xbb;&#x420;&#xb0;&#x420;&#x406;&#x420;&#x405;&#x421;&#x2039;&#x420;&#xb5; &#x421;&#x201e;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x421;&#x2039; &#x421;&#x402;&#x420;&#xb5;&#x420;&#x491;&#x420;&#xb0;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x451;&#x421;&#x402;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemId" lowerBound="1" eType="//DataModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIElement" abstract="true">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x2019;&#x420;&#x451;&#x420;&#xb7;&#x421;&#x453;&#x420;&#xb0;&#x420;&#xbb;&#x421;&#x40a;&#x420;&#x405;&#x421;&#x2039;&#x420;&#x2116; &#x421;&#x40c;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;"/>
      <details key="caption.plural" value="&#x420;&#x2019;&#x420;&#x451;&#x420;&#xb7;&#x421;&#x453;&#x420;&#xb0;&#x420;&#xbb;&#x421;&#x40a;&#x420;&#x405;&#x421;&#x2039;&#x420;&#xb5; &#x421;&#x40c;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x421;&#x2039;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45c;&#x420;&#xb0;&#x420;&#x451;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x2014;&#x420;&#xb0;&#x420;&#x456;&#x420;&#x455;&#x420;&#xbb;&#x420;&#x455;&#x420;&#x406;&#x420;&#x455;&#x420;&#x454;"/>
        <details key="display" value="true"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hint">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45f;&#x420;&#x455;&#x420;&#x491;&#x421;&#x403;&#x420;&#x454;&#x420;&#xb0;&#x420;&#xb7;&#x420;&#x454;&#x420;&#xb0;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hideOn" eType="//OrExpression" containment="true">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x408;&#x421;&#x403;&#x420;&#xbb;&#x420;&#x455;&#x420;&#x406;&#x420;&#x451;&#x421;&#x40f; &#x420;&#x405;&#x420;&#xb5;&#x420;&#x406;&#x420;&#x451;&#x420;&#x491;&#x420;&#x451;&#x420;&#x458;&#x420;&#x455;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x451;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disableOn" eType="//OrExpression" containment="true">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x408;&#x421;&#x403;&#x420;&#xbb;&#x420;&#x455;&#x420;&#x406;&#x420;&#x451;&#x421;&#x40f; &#x420;&#x405;&#x420;&#xb5;&#x420;&#x491;&#x420;&#x455;&#x421;&#x403;&#x421;&#x201a;&#x421;&#x453;&#x420;&#x457;&#x420;&#x405;&#x420;&#x455;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x451;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutElement" abstract="true" eSuperTypes="//UIElement">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;"/>
      <details key="caption.plural" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x421;&#x2039;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" eType="//Layout" eOpposite="//Layout/elements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layout" abstract="true" eSuperTypes="//LayoutElement">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x459;&#x420;&#x455;&#x420;&#x405;&#x421;&#x201a;&#x420;&#xb5;&#x420;&#x2116;&#x420;&#x405;&#x420;&#xb5;&#x421;&#x402; &#x421;&#x40c;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x406;"/>
      <details key="caption.plural" value="&#x420;&#x459;&#x420;&#x455;&#x420;&#x405;&#x421;&#x201a;&#x420;&#xb5;&#x420;&#x2116;&#x420;&#x405;&#x420;&#xb5;&#x421;&#x402;&#x421;&#x2039; &#x421;&#x40c;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x406;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1" eType="//LayoutElement" containment="true" eOpposite="//LayoutElement/layout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RowLayout" eSuperTypes="//Layout">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x201c;&#x420;&#x455;&#x421;&#x402;&#x420;&#x451;&#x420;&#xb7;&#x420;&#x455;&#x420;&#x405;&#x421;&#x201a;&#x420;&#xb0;&#x420;&#xbb;&#x421;&#x40a;&#x420;&#x405;&#x421;&#x2039;&#x420;&#x2116; &#x420;&#x454;&#x420;&#x455;&#x420;&#x405;&#x421;&#x201a;&#x420;&#xb5;&#x420;&#x2116;&#x420;&#x405;&#x420;&#xb5;&#x421;&#x402;"/>
      <details key="caption.plural" value="&#x420;&#x201c;&#x420;&#x455;&#x421;&#x402;&#x420;&#x451;&#x420;&#xb7;&#x420;&#x455;&#x420;&#x405;&#x421;&#x201a;&#x420;&#xb0;&#x420;&#xbb;&#x421;&#x40a;&#x420;&#x405;&#x421;&#x2039;&#x420;&#xb5; &#x420;&#x454;&#x420;&#x455;&#x420;&#x405;&#x421;&#x201a;&#x420;&#xb5;&#x420;&#x2116;&#x420;&#x405;&#x420;&#xb5;&#x421;&#x402;&#x421;&#x2039;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnLayout" eSuperTypes="//Layout">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x2019;&#x420;&#xb5;&#x421;&#x402;&#x421;&#x201a;&#x420;&#x451;&#x420;&#x454;&#x420;&#xb0;&#x420;&#xbb;&#x421;&#x40a;&#x420;&#x405;&#x421;&#x2039;&#x420;&#x2116; &#x420;&#x454;&#x420;&#x455;&#x420;&#x405;&#x421;&#x201a;&#x420;&#xb5;&#x420;&#x2116;&#x420;&#x405;&#x420;&#xb5;&#x421;&#x402;"/>
      <details key="caption.plural" value="&#x420;&#x2019;&#x420;&#xb5;&#x421;&#x402;&#x421;&#x201a;&#x420;&#x451;&#x420;&#x454;&#x420;&#xb0;&#x420;&#xbb;&#x421;&#x40a;&#x420;&#x405;&#x421;&#x2039;&#x420;&#xb5; &#x420;&#x454;&#x420;&#x455;&#x420;&#x405;&#x421;&#x201a;&#x420;&#xb5;&#x420;&#x2116;&#x420;&#x405;&#x420;&#xb5;&#x421;&#x402;&#x421;&#x2039;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupListLayout" eSuperTypes="//Layout">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x40e;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x455;&#x420;&#x454; &#x420;&#x456;&#x421;&#x402;&#x421;&#x453;&#x420;&#x457;&#x420;&#x457; &#x421;&#x40c;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x406;"/>
      <details key="caption.plural" value="&#x420;&#x40e;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x455;&#x420;&#x454;&#x420;&#x451; &#x420;&#x456;&#x421;&#x402;&#x421;&#x453;&#x420;&#x457;&#x420;&#x457; &#x421;&#x40c;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x406;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showStyle" eType="//GroupListStyleEnum" defaultValueLiteral="SHOW_FIRST"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormLayout" eSuperTypes="//Layout">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x45f;&#x421;&#x402;&#x420;&#x455;&#x421;&#x403;&#x421;&#x201a;&#x420;&#xb0;&#x421;&#x40f; &#x421;&#x201e;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#x45f;&#x421;&#x402;&#x420;&#x455;&#x421;&#x403;&#x421;&#x201a;&#x421;&#x2039;&#x420;&#xb5; &#x421;&#x201e;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x421;&#x2039;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataControl" abstract="true" eSuperTypes="//LayoutElement">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
      <details key="caption.plural" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x421;&#x2039; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataModel" lowerBound="1" eType="//DataModel">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#xa0;&#x420;&#xb5;&#x420;&#x491;&#x420;&#xb0;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x451;&#x421;&#x402;&#x421;&#x453;&#x420;&#xb5;&#x420;&#x458;&#x421;&#x2039;&#x420;&#x2116; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredOn" eType="//OrExpression" containment="true">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x408;&#x421;&#x403;&#x420;&#xbb;&#x420;&#x455;&#x420;&#x406;&#x420;&#x451;&#x421;&#x40f; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x40f;&#x420;&#xb7;&#x420;&#xb0;&#x421;&#x201a;&#x420;&#xb5;&#x420;&#xbb;&#x421;&#x40a;&#x420;&#x405;&#x420;&#x455;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x451;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionControl" eSuperTypes="//DataControl">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a; &#x420;&#x406;&#x421;&#x2039;&#x420;&#xb1;&#x420;&#x455;&#x421;&#x402;&#x420;&#xb0; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
      <details key="caption.plural" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x421;&#x2039; &#x420;&#x406;&#x421;&#x2039;&#x420;&#xb1;&#x420;&#x455;&#x421;&#x402;&#x420;&#xb0; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refModel" lowerBound="1" eType="//DataModel">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x40e;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x455;&#x420;&#x454; &#x420;&#x406;&#x421;&#x2039;&#x420;&#xb1;&#x420;&#x455;&#x421;&#x402;&#x420;&#xb0;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x459;&#x420;&#xbb;&#x421;&#x40b;&#x421;&#x2021;&#x420;&#xb5;&#x420;&#x406;&#x420;&#x455;&#x420;&#xb5; &#x420;&#x457;&#x420;&#x455;&#x420;&#xbb;&#x420;&#xb5;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="display">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45f;&#x420;&#x455;&#x420;&#xbb;&#x420;&#xb5; &#x420;&#x491;&#x420;&#xbb;&#x421;&#x40f; &#x420;&#x455;&#x421;&#x201a;&#x420;&#x455;&#x420;&#xb1;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45a;&#x420;&#xb0;&#x420;&#x454;&#x421;&#x403;&#x420;&#x451;&#x420;&#x458;&#x420;&#xb0;&#x420;&#xbb;&#x421;&#x40a;&#x420;&#x405;&#x420;&#x455;&#x420;&#xb5; &#x420;&#x454;&#x420;&#x455;&#x420;&#xbb;&#x420;&#x451;&#x421;&#x2021;&#x420;&#xb5;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x406;&#x420;&#x455; &#x420;&#x406;&#x421;&#x2039;&#x420;&#xb1;&#x421;&#x402;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x406;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextControl" eSuperTypes="//DataControl">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x421;&#x201a;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x403;&#x421;&#x201a;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x421;&#x2039; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x421;&#x201a;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x403;&#x421;&#x201a;&#x420;&#xb0;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiline" defaultValueLiteral="false">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45a;&#x420;&#x405;&#x420;&#x455;&#x420;&#x456;&#x420;&#x455;&#x421;&#x403;&#x421;&#x201a;&#x421;&#x402;&#x420;&#x455;&#x421;&#x2021;&#x420;&#x405;&#x421;&#x2039;&#x420;&#x2116;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" defaultValueLiteral="false">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45f;&#x420;&#xb0;&#x421;&#x402;&#x420;&#x455;&#x420;&#xbb;&#x421;&#x40a;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmbeddedListControl" eSuperTypes="//DataControl">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x421;&#x403;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x454;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x421;&#x2039; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x421;&#x403;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x454;&#x420;&#xb0;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberControl" eSuperTypes="//DataControl">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x421;&#x2021;&#x420;&#x451;&#x421;&#x403;&#x420;&#xbb;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x421;&#x2039; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x421;&#x2021;&#x420;&#x451;&#x421;&#x403;&#x420;&#xb5;&#x420;&#xbb;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateControl" eSuperTypes="//DataControl">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x420;&#x491;&#x420;&#xb0;&#x421;&#x201a;&#x421;&#x2039;"/>
      <details key="caption.plural" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x421;&#x2039; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x420;&#x491;&#x420;&#xb0;&#x421;&#x201a;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateTimeControl" eSuperTypes="//DataControl">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x420;&#x491;&#x420;&#xb0;&#x421;&#x201a;&#x421;&#x2039; &#x420;&#x451; &#x420;&#x406;&#x421;&#x402;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;"/>
      <details key="caption.plural" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x421;&#x2039; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x420;&#x491;&#x420;&#xb0;&#x421;&#x201a; &#x420;&#x451; &#x420;&#x406;&#x421;&#x402;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanControl" eSuperTypes="//DataControl">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x420;&#xbb;&#x420;&#x455;&#x420;&#x456;&#x420;&#x451;&#x421;&#x2021;&#x420;&#xb5;&#x421;&#x403;&#x420;&#x454;&#x420;&#x455;&#x420;&#x456;&#x420;&#x455; &#x420;&#xb7;&#x420;&#x405;&#x420;&#xb0;&#x421;&#x2021;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
      <details key="caption.plural" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x421;&#x2039; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x420;&#xbb;&#x420;&#x455;&#x420;&#x456;&#x420;&#x451;&#x421;&#x2021;&#x420;&#xb5;&#x421;&#x403;&#x420;&#x454;&#x420;&#x455;&#x420;&#x456;&#x420;&#x455; &#x420;&#xb7;&#x420;&#x405;&#x420;&#xb0;&#x421;&#x2021;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassControl" abstract="true" eSuperTypes="//DataControl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiClass" lowerBound="1" eType="//UIClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditFormControl" eSuperTypes="//ClassControl">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x420;&#xb7;&#x420;&#x405;&#x420;&#xb0;&#x421;&#x2021;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#xad;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x201a;&#x421;&#x2039; &#x420;&#x406;&#x420;&#x406;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb0; &#x420;&#xb7;&#x420;&#x405;&#x420;&#xb0;&#x421;&#x2021;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x420;&#x2116; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x406;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainEditFormControl" eSuperTypes="//EditFormControl">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x201c;&#x420;&#xbb;&#x420;&#xb0;&#x420;&#x406;&#x420;&#x405;&#x420;&#xb0;&#x421;&#x40f; &#x421;&#x201e;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x420;&#xb0; &#x421;&#x402;&#x420;&#xb5;&#x420;&#x491;&#x420;&#xb0;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x451;&#x421;&#x402;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#x201c;&#x420;&#xbb;&#x420;&#xb0;&#x420;&#x406;&#x420;&#x405;&#x421;&#x2039;&#x420;&#xb5; &#x421;&#x201e;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x421;&#x2039; &#x421;&#x402;&#x420;&#xb5;&#x420;&#x491;&#x420;&#xb0;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x451;&#x421;&#x402;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x406;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableControl" abstract="true" eSuperTypes="//ClassControl">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x45e;&#x420;&#xb0;&#x420;&#xb1;&#x420;&#xbb;&#x420;&#x451;&#x421;&#x2020;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#x45e;&#x420;&#xb0;&#x420;&#xb1;&#x420;&#xbb;&#x420;&#x451;&#x421;&#x2020;&#x421;&#x2039;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1" eType="//TableColumn" containment="true" eOpposite="//TableColumn/table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableColumn" eSuperTypes="//UIElement">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x459;&#x420;&#x455;&#x420;&#xbb;&#x420;&#x455;&#x420;&#x405;&#x420;&#x454;&#x420;&#xb0; &#x421;&#x201a;&#x420;&#xb0;&#x420;&#xb1;&#x420;&#xbb;&#x420;&#x451;&#x421;&#x2020;&#x421;&#x2039;"/>
      <details key="caption.plural" value="&#x420;&#x459;&#x420;&#x455;&#x420;&#xbb;&#x420;&#x455;&#x420;&#x405;&#x420;&#x454;&#x420;&#x451; &#x421;&#x201a;&#x420;&#xb0;&#x420;&#xb1;&#x420;&#xbb;&#x420;&#x451;&#x421;&#x2020;&#x421;&#x2039;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="//TableControl" eOpposite="//TableControl/columns"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MasterDetail" eSuperTypes="//TableControl">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x45e;&#x420;&#xb0;&#x420;&#xb1;&#x420;&#xbb;&#x420;&#x451;&#x421;&#x2020;&#x420;&#xb0; &#x421;&#x403; &#x420;&#x406;&#x420;&#x405;&#x421;&#x453;&#x421;&#x201a;&#x421;&#x402;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x405;&#x420;&#x451;&#x420;&#x458; &#x421;&#x402;&#x420;&#xb5;&#x420;&#x491;&#x420;&#xb0;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x451;&#x421;&#x402;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;&#x420;&#x458;"/>
      <details key="caption.plural" value="&#x420;&#x45e;&#x420;&#xb0;&#x420;&#xb1;&#x420;&#xbb;&#x420;&#x451;&#x421;&#x2020;&#x421;&#x2039; &#x421;&#x403; &#x420;&#x406;&#x420;&#x405;&#x421;&#x453;&#x421;&#x201a;&#x421;&#x402;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x405;&#x420;&#x451;&#x420;&#x458; &#x421;&#x402;&#x420;&#xb5;&#x420;&#x491;&#x420;&#xb0;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x451;&#x421;&#x402;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;&#x420;&#x458;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableGroupControl" eSuperTypes="//TableControl">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x45e;&#x420;&#xb0;&#x420;&#xb1;&#x420;&#xbb;&#x420;&#x451;&#x421;&#x2020;&#x420;&#xb0; &#x421;&#x403; &#x420;&#x406;&#x420;&#x405;&#x420;&#xb5;&#x421;&#x20ac;&#x420;&#x405;&#x420;&#x451;&#x420;&#x458; &#x421;&#x402;&#x420;&#xb5;&#x420;&#x491;&#x420;&#xb0;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x451;&#x421;&#x402;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;&#x420;&#x458;"/>
      <details key="caption.plural" value="&#x420;&#x45e;&#x420;&#xb0;&#x420;&#xb1;&#x420;&#xbb;&#x420;&#x451;&#x421;&#x2020;&#x421;&#x2039; &#x421;&#x403; &#x420;&#x406;&#x420;&#x405;&#x420;&#xb5;&#x421;&#x20ac;&#x420;&#x405;&#x420;&#x451;&#x420;&#x458; &#x421;&#x402;&#x420;&#xb5;&#x420;&#x491;&#x420;&#xb0;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x451;&#x421;&#x402;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;&#x420;&#x458;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphControl" eSuperTypes="//ClassControl">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x201d;&#x420;&#x451;&#x420;&#xb0;&#x420;&#x456;&#x421;&#x402;&#x420;&#xb0;&#x420;&#x458;&#x420;&#x458;&#x420;&#xb0; &#x420;&#x201c;&#x420;&#xb0;&#x420;&#x405;&#x421;&#x201a;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#x201d;&#x420;&#x451;&#x420;&#xb0;&#x420;&#x456;&#x421;&#x402;&#x420;&#xb0;&#x420;&#x458;&#x421;&#x2039; &#x420;&#x201c;&#x420;&#xb0;&#x420;&#x405;&#x421;&#x201a;&#x420;&#xb0;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x2019;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
      <details key="caption.plural" value="&#x420;&#x2019;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" abstract="true" eSuperTypes="//Expression">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x203a;&#x420;&#x455;&#x420;&#x456;&#x420;&#x451;&#x421;&#x2021;&#x420;&#xb5;&#x421;&#x403;&#x420;&#x454;&#x420;&#x455;&#x420;&#xb5; &#x420;&#x406;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
      <details key="caption.plural" value="&#x420;&#x203a;&#x420;&#x455;&#x420;&#x456;&#x420;&#x451;&#x421;&#x2021;&#x420;&#xb5;&#x421;&#x403;&#x420;&#x454;&#x420;&#x451;&#x420;&#xb5; &#x420;&#x406;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvalBooleanExpression" eSuperTypes="//BooleanExpression">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x2019;&#x421;&#x2039;&#x421;&#x2021;&#x420;&#x451;&#x421;&#x403;&#x420;&#xbb;&#x421;&#x40f;&#x420;&#xb5;&#x420;&#x458;&#x420;&#x455;&#x420;&#xb5; &#x420;&#xbb;&#x420;&#x455;&#x420;&#x456;&#x420;&#x451;&#x421;&#x2021;&#x420;&#xb5;&#x421;&#x403;&#x420;&#x454;&#x420;&#x455;&#x420;&#xb5; &#x420;&#x406;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
      <details key="caption.plural" value="&#x420;&#x2019;&#x421;&#x2039;&#x421;&#x2021;&#x420;&#x451;&#x421;&#x403;&#x420;&#xbb;&#x421;&#x40f;&#x420;&#xb5;&#x420;&#x458;&#x421;&#x2039;&#x420;&#xb5; &#x420;&#xbb;&#x420;&#x455;&#x420;&#x456;&#x420;&#x451;&#x421;&#x2021;&#x420;&#xb5;&#x421;&#x403;&#x420;&#x454;&#x420;&#x451;&#x420;&#xb5; &#x420;&#x406;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expr">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataModelComparison" abstract="true" eSuperTypes="//EvalBooleanExpression">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x2019;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5; &#x421;&#x403;&#x421;&#x402;&#x420;&#xb0;&#x420;&#x406;&#x420;&#x405;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
      <details key="caption.plural" value="&#x420;&#x2019;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f; &#x421;&#x403;&#x421;&#x402;&#x420;&#xb0;&#x420;&#x406;&#x420;&#x405;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataModel" lowerBound="1" eType="//DataModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EqEvalExpression" eSuperTypes="//DataModelComparison">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x2019;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5; &#x421;&#x402;&#x420;&#xb0;&#x420;&#x406;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x406;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#x2019;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f; &#x421;&#x402;&#x420;&#xb0;&#x420;&#x406;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x406;&#x420;&#xb0;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NeEvalExpression" eSuperTypes="//DataModelComparison">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x2019;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5; &#x420;&#x405;&#x420;&#xb5;&#x421;&#x402;&#x420;&#xb0;&#x420;&#x406;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x406;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#x2019;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f; &#x420;&#x405;&#x420;&#xb5;&#x421;&#x402;&#x420;&#xb0;&#x420;&#x406;&#x420;&#xb5;&#x420;&#x405;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x406;&#x420;&#xb0;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListExpression" abstract="true" eSuperTypes="//BooleanExpression">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x40e;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x455;&#x420;&#x454; &#x420;&#xbb;&#x420;&#x455;&#x420;&#x456;&#x420;&#x451;&#x421;&#x2021;&#x420;&#xb5;&#x421;&#x403;&#x420;&#x454;&#x420;&#x451;&#x421;&#x2026; &#x420;&#x406;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x420;&#x2116;"/>
      <details key="caption.plural" value="&#x420;&#x40e;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x454;&#x420;&#x451; &#x420;&#xbb;&#x420;&#x455;&#x420;&#x456;&#x420;&#x451;&#x421;&#x2021;&#x420;&#xb5;&#x421;&#x403;&#x420;&#x454;&#x420;&#x451;&#x421;&#x2026; &#x420;&#x406;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x420;&#x2116;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1" eType="//BooleanExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndExpression" eSuperTypes="//ListExpression">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x203a;&#x420;&#x455;&#x420;&#x456;&#x420;&#x451;&#x421;&#x2021;&#x420;&#xb5;&#x421;&#x403;&#x420;&#x454;&#x420;&#x455;&#x420;&#xb5; &#x420;&#xfffd;"/>
      <details key="caption.plural" value="&#x420;&#x40e;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x455;&#x420;&#x454; &#x420;&#xbb;&#x420;&#x455;&#x420;&#x456;&#x420;&#x451;&#x421;&#x2021;&#x420;&#xb5;&#x421;&#x403;&#x420;&#x454;&#x420;&#x451;&#x421;&#x2026; &#x420;&#xfffd;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrExpression" eSuperTypes="//ListExpression">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x203a;&#x420;&#x455;&#x420;&#x456;&#x420;&#x451;&#x421;&#x2021;&#x420;&#xb5;&#x421;&#x403;&#x420;&#x454;&#x420;&#x455;&#x420;&#xb5; &#x420;&#xfffd;&#x420;&#x203a;&#x420;&#xfffd;"/>
      <details key="caption.plural" value="&#x420;&#x40e;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x455;&#x420;&#x454; &#x420;&#xbb;&#x420;&#x455;&#x420;&#x456;&#x420;&#x451;&#x421;&#x2021;&#x420;&#xb5;&#x421;&#x403;&#x420;&#x454;&#x420;&#x451;&#x421;&#x2026; &#x420;&#xfffd;&#x420;&#x203a;&#x420;&#xfffd;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataModel" abstract="true">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x45a;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb5;&#x420;&#xbb;&#x421;&#x40a; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
      <details key="caption.plural" value="&#x420;&#x45a;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb5;&#x420;&#xbb;&#x420;&#x451; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45c;&#x420;&#xb0;&#x420;&#x451;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
        <details key="display" value="true"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//ModelProperty" containment="true" eOpposite="//ModelProperty/model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelProperty" eSuperTypes="//DataModel">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x40e;&#x420;&#x406;&#x420;&#x455;&#x420;&#x2116;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x406;&#x420;&#x455; &#x420;&#x458;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb5;&#x420;&#xbb;&#x420;&#x451; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
      <details key="caption.plural" value="&#x420;&#x40e;&#x420;&#x406;&#x420;&#x455;&#x420;&#x2116;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x406;&#x420;&#xb0; &#x420;&#x458;&#x420;&#x455;&#x420;&#x491;&#x420;&#xb5;&#x420;&#xbb;&#x420;&#x451; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="//DataModel" eOpposite="//DataModel/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" abstract="true" eSuperTypes="//DataModel">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#xfffd;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x421;&#x2021;&#x420;&#x405;&#x420;&#x451;&#x420;&#x454; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
      <details key="caption.plural" value="&#x420;&#xfffd;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x421;&#x2021;&#x420;&#x405;&#x420;&#x451;&#x420;&#x454;&#x420;&#x451; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="form" lowerBound="1" eType="//UIForm" eOpposite="//UIForm/dataSources"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="//DataSource">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x45f;&#x420;&#xb0;&#x421;&#x402;&#x420;&#xb0;&#x420;&#x458;&#x420;&#xb5;&#x421;&#x201a;&#x421;&#x402; &#x421;&#x201e;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x421;&#x2039;"/>
      <details key="caption.plural" value="&#x420;&#x45f;&#x420;&#xb0;&#x421;&#x402;&#x420;&#xb0;&#x420;&#x458;&#x420;&#xb5;&#x421;&#x201a;&#x421;&#x402;&#x421;&#x2039; &#x421;&#x201e;&#x420;&#x455;&#x421;&#x402;&#x420;&#x458;&#x421;&#x2039;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eval" eSuperTypes="//DataSource">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x2019;&#x421;&#x2039;&#x421;&#x2021;&#x420;&#x451;&#x421;&#x403;&#x420;&#xbb;&#x421;&#x40f;&#x420;&#xb5;&#x420;&#x458;&#x421;&#x2039;&#x420;&#x2116; &#x420;&#x451;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x421;&#x2021;&#x420;&#x405;&#x420;&#x451;&#x420;&#x454; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
      <details key="caption.plural" value="&#x420;&#x2019;&#x421;&#x2039;&#x421;&#x2021;&#x420;&#x451;&#x421;&#x403;&#x420;&#xbb;&#x421;&#x40f;&#x420;&#xb5;&#x420;&#x458;&#x421;&#x2039;&#x420;&#xb5; &#x420;&#x451;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x421;&#x2021;&#x420;&#x405;&#x420;&#x451;&#x420;&#x454;&#x420;&#x451; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expr" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalSource" eSuperTypes="//DataSource">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x2019;&#x420;&#x405;&#x420;&#xb5;&#x421;&#x20ac;&#x420;&#x405;&#x420;&#x451;&#x420;&#x2116; &#x420;&#x451;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x421;&#x2021;&#x420;&#x405;&#x420;&#x451;&#x420;&#x454; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
      <details key="caption.plural" value="&#x420;&#x2019;&#x420;&#x405;&#x420;&#xb5;&#x421;&#x20ac;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5; &#x420;&#x451;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x421;&#x2021;&#x420;&#x405;&#x420;&#x451;&#x420;&#x454;&#x420;&#x451; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Null" eSuperTypes="//DataSource">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x45f;&#x421;&#x453;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x2116; &#x420;&#x451;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x421;&#x2021;&#x420;&#x405;&#x420;&#x451;&#x420;&#x454; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
      <details key="caption.plural" value="&#x420;&#x45f;&#x421;&#x453;&#x421;&#x403;&#x421;&#x201a;&#x421;&#x2039;&#x420;&#xb5; &#x420;&#x451;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x421;&#x2021;&#x420;&#x405;&#x420;&#x451;&#x420;&#x454;&#x420;&#x451; &#x420;&#x491;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBSource" abstract="true" eSuperTypes="//DataSource">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x2014;&#x420;&#xb0;&#x420;&#x457;&#x421;&#x402;&#x420;&#x455;&#x421;&#x403; &#x420;&#x454; &#x420;&#x2018;&#x420;&#x201d;"/>
      <details key="caption.plural" value="&#x420;&#x2014;&#x420;&#xb0;&#x420;&#x457;&#x421;&#x402;&#x420;&#x455;&#x421;&#x403;&#x421;&#x2039; &#x420;&#x454; &#x420;&#x2018;&#x420;&#x201d;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="up" defaultValueLiteral="-2">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="down" defaultValueLiteral="-2">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deep" defaultValueLiteral="-2">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuerySource" abstract="true" eSuperTypes="//DBSource">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="SQL &#x420;&#xb7;&#x420;&#xb0;&#x420;&#x457;&#x421;&#x402;&#x420;&#x455;&#x421;&#x403;"/>
      <details key="caption.plural" value="SQL &#x420;&#xb7;&#x420;&#xb0;&#x420;&#x457;&#x421;&#x402;&#x420;&#x455;&#x421;&#x403;&#x421;&#x2039;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectSource" abstract="true" eSuperTypes="//DBSource">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x2014;&#x420;&#xb0;&#x420;&#x457;&#x421;&#x402;&#x420;&#x455;&#x421;&#x403; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#x2014;&#x420;&#xb0;&#x420;&#x457;&#x421;&#x402;&#x420;&#x455;&#x421;&#x403;&#x421;&#x2039; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x406;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiClass" lowerBound="1" eType="//UIClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectItem" eSuperTypes="//ObjectSource">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x2014;&#x420;&#xb0;&#x420;&#x457;&#x421;&#x402;&#x420;&#x455;&#x421;&#x403; &#x420;&#xb5;&#x420;&#x491;&#x420;&#x451;&#x420;&#x405;&#x420;&#x451;&#x421;&#x2021;&#x420;&#x405;&#x420;&#x455;&#x420;&#x456;&#x420;&#x455; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#x2014;&#x420;&#xb0;&#x420;&#x457;&#x421;&#x402;&#x420;&#x455;&#x421;&#x403;&#x421;&#x2039; &#x420;&#xb5;&#x420;&#x491;&#x420;&#x451;&#x420;&#x405;&#x420;&#x451;&#x421;&#x2021;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x406;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modeModel" lowerBound="1" eType="//DataModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectList" eSuperTypes="//ObjectSource">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x2014;&#x420;&#xb0;&#x420;&#x457;&#x421;&#x402;&#x420;&#x455;&#x421;&#x403; &#x421;&#x403;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x454;&#x420;&#xb0; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#xb0;"/>
      <details key="caption.plural" value="&#x420;&#x2014;&#x420;&#xb0;&#x420;&#x457;&#x421;&#x402;&#x420;&#x455;&#x421;&#x403;&#x421;&#x2039; &#x421;&#x403;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x454;&#x420;&#x455;&#x420;&#x406; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x406;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" eType="//AndExpression" containment="true">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#xa4;&#x420;&#x451;&#x420;&#xbb;&#x421;&#x40a;&#x421;&#x201a;&#x421;&#x402;"/>
        <details key="caption.plural" value="&#x420;&#xa4;&#x420;&#x451;&#x420;&#xbb;&#x421;&#x40a;&#x421;&#x201a;&#x421;&#x402;&#x421;&#x2039;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joined" upperBound="-1" eType="//JoinedObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fname" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="falias" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstObjectList" eSuperTypes="//DataSource">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x40e;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x455;&#x420;&#x454; &#x420;&#x457;&#x420;&#x455;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x421;&#x40f;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x406;"/>
      <details key="caption.plural" value="&#x420;&#x40e;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x454;&#x420;&#x451; &#x420;&#x457;&#x420;&#x455;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x421;&#x40f;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x421;&#x2026; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x420;&#x455;&#x420;&#x406;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1" eType="//ConstObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstObject">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x45f;&#x420;&#x455;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x421;&#x40f;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x420;&#x2116; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;"/>
      <details key="caption.plural" value="&#x420;&#x45f;&#x420;&#x455;&#x421;&#x403;&#x421;&#x201a;&#x420;&#x455;&#x421;&#x40f;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x420;&#xb5; &#x420;&#x455;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x421;&#x2039;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1" eType="//NamedExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedExpression">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#xfffd;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x420;&#x455;&#x420;&#xb5; &#x420;&#x406;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
      <details key="caption.plural" value="&#x420;&#xfffd;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x405;&#x421;&#x2039;&#x420;&#xb5; &#x420;&#x406;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x421;&#x40f;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45c;&#x420;&#xb0;&#x420;&#x451;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
        <details key="display" value="true"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expr">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x2019;&#x421;&#x2039;&#x421;&#x402;&#x420;&#xb0;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x45f;&#x421;&#x402;&#x420;&#x451;&#x420;&#xbb;&#x420;&#x455;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
      <details key="caption.plural" value="&#x420;&#x40e;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x455;&#x420;&#x454; &#x420;&#x457;&#x421;&#x402;&#x420;&#x451;&#x420;&#xbb;&#x420;&#x455;&#x420;&#xb6;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x451;&#x420;&#x2116;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45c;&#x420;&#xb0;&#x420;&#x451;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x2014;&#x420;&#xb0;&#x420;&#x456;&#x420;&#x455;&#x420;&#xbb;&#x420;&#x455;&#x420;&#x406;&#x420;&#x455;&#x420;&#x454;"/>
        <details key="display" value="true"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1" eType="//Module" containment="true" eOpposite="//Module/application"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x45a;&#x420;&#x455;&#x420;&#x491;&#x421;&#x453;&#x420;&#xbb;&#x421;&#x40a;"/>
      <details key="caption.plural" value="&#x420;&#x40e;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x455;&#x420;&#x454; &#x420;&#x458;&#x420;&#x455;&#x420;&#x491;&#x421;&#x453;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x2116;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" lowerBound="1" eType="//Application" eOpposite="//Application/modules"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45c;&#x420;&#xb0;&#x420;&#x451;&#x420;&#x458;&#x420;&#xb5;&#x420;&#x405;&#x420;&#x455;&#x420;&#x406;&#x420;&#xb0;&#x420;&#x405;&#x420;&#x451;&#x420;&#xb5;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x2014;&#x420;&#xb0;&#x420;&#x456;&#x420;&#x455;&#x420;&#xbb;&#x420;&#x455;&#x420;&#x406;&#x420;&#x455;&#x420;&#x454;"/>
        <details key="display" value="true"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryClasses" upperBound="-1" eType="//UIClass">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x45b;&#x420;&#xb1;&#x421;&#x409;&#x420;&#xb5;&#x420;&#x454;&#x421;&#x201a;&#x421;&#x2039; &#x420;&#x458;&#x420;&#x455;&#x420;&#x491;&#x421;&#x453;&#x420;&#xbb;&#x421;&#x40f;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalModule" eSuperTypes="//Module">
    <eAnnotations source="mspace.ui">
      <details key="caption" value="&#x420;&#x2019;&#x420;&#x405;&#x420;&#xb5;&#x421;&#x20ac;&#x420;&#x405;&#x420;&#x451;&#x420;&#x2116; &#x420;&#x45a;&#x420;&#x455;&#x420;&#x491;&#x421;&#x453;&#x420;&#xbb;&#x421;&#x40a;"/>
      <details key="caption.plural" value="&#x420;&#x40e;&#x420;&#x457;&#x420;&#x451;&#x421;&#x403;&#x420;&#x455;&#x420;&#x454; &#x420;&#x406;&#x420;&#x405;&#x420;&#xb5;&#x421;&#x20ac;&#x420;&#x405;&#x420;&#x451;&#x421;&#x2026; &#x420;&#x458;&#x420;&#x455;&#x420;&#x491;&#x421;&#x453;&#x420;&#xbb;&#x420;&#xb5;&#x420;&#x2116;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link">
      <eAnnotations source="mspace.ui">
        <details key="caption" value="&#x420;&#x40e;&#x421;&#x403;&#x421;&#x2039;&#x420;&#xbb;&#x420;&#x454;&#x420;&#xb0;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GroupListStyleEnum">
    <eLiterals name="SHOW_ALL" value="1"/>
    <eLiterals name="SHOW_FIRST" value="2"/>
    <eLiterals name="HIDE_ALL" value="3"/>
  </eClassifiers>
</ecore:EPackage>
