import ru.neoflex.meta.utils.Context
def session = Context.current.txSession
def entity = session.createQuery("from rt.CoordinatorDeployment where name = :name").setParameter("name", "autogenerated_co_co_load_datagram_transformations").uniqueResult() 
entity.deployments.clear()
entity.workflows.clear()
entity.project = session.createQuery("from etl.Project where name = :name").setParameter("name", "autogenerated").uniqueResult()
entity.oozie = session.createQuery("from rt.Oozie where name = :name").setParameter("name", "bd-oozie").uniqueResult()
entity.deployments.add(session.createQuery("from rt.Deployment where name = :name").setParameter("name", "teneo").uniqueResult())
entity.deployments.add(session.createQuery("from rt.Deployment where name = :name").setParameter("name", "awSales").uniqueResult())
entity.coordinator = session.createQuery("from etl.CoJob where name = :name").setParameter("name", "co_load_datagram_transformations").uniqueResult()
Context.current.commit()
