import ru.neoflex.meta.utils.Context
def session = Context.current.txSession
def entity = session.createQuery("from rt.WorkflowDeployment where name = :name").setParameter("name", "autogenerated_wf_wf_1c_rest").uniqueResult() 
entity.deployments.clear()
entity.workflows.clear()
entity.project = session.createQuery("from etl.Project where name = :name").setParameter("name", "autogenerated").uniqueResult()
entity.oozie = session.createQuery("from rt.Oozie where name = :name").setParameter("name", "bd-oozie").uniqueResult()
entity.start = session.createQuery("from etl.Workflow where name = :name").setParameter("name", "wf_1c_rest").uniqueResult()
Context.current.commit()
